// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'crud/entities/person.dart';
import 'query_builder/entities/motor_cycle.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5811696278053571529),
      name: 'Person',
      lastPropertyId: const IdUid(2, 4059369099839415075),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2766492957406758840),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4059369099839415075),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 6608405557237770385),
      name: 'MotorCycle',
      lastPropertyId: const IdUid(4, 1276955091263858364),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1584732101324358645),
            name: 'motorcycleId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2235527276287615992),
            name: 'serialNumber',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 2023347072540181795)),
        ModelProperty(
            id: const IdUid(3, 2395857057928376758),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1276955091263858364),
            name: 'releaseYear',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 6608405557237770385),
      lastIndexId: const IdUid(1, 2023347072540181795),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Person: EntityDefinition<Person>(
        model: _entities[0],
        toOneRelations: (Person object) => [],
        toManyRelations: (Person object) => {},
        getId: (Person object) => object.id,
        setId: (Person object, int id) {
          object.id = id;
        },
        objectToFB: (Person object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Person(id: idParam, name: nameParam);

          return object;
        }),
    MotorCycle: EntityDefinition<MotorCycle>(
        model: _entities[1],
        toOneRelations: (MotorCycle object) => [],
        toManyRelations: (MotorCycle object) => {},
        getId: (MotorCycle object) => object.motorcycleId,
        setId: (MotorCycle object, int id) {
          object.motorcycleId = id;
        },
        objectToFB: (MotorCycle object, fb.Builder fbb) {
          final serialNumberOffset = fbb.writeString(object.serialNumber);
          final nameOffset = fbb.writeString(object.name);
          final releaseYearOffset = fbb.writeString(object.releaseYear);
          fbb.startTable(5);
          fbb.addInt64(0, object.motorcycleId);
          fbb.addOffset(1, serialNumberOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, releaseYearOffset);
          fbb.finish(fbb.endTable());
          return object.motorcycleId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final motorcycleIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final serialNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final releaseYearParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final object = MotorCycle(
              motorcycleId: motorcycleIdParam,
              serialNumber: serialNumberParam,
              name: nameParam,
              releaseYear: releaseYearParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Person] entity fields to define ObjectBox queries.
class Person_ {
  /// see [Person.id]
  static final id = QueryIntegerProperty<Person>(_entities[0].properties[0]);

  /// see [Person.name]
  static final name = QueryStringProperty<Person>(_entities[0].properties[1]);
}

/// [MotorCycle] entity fields to define ObjectBox queries.
class MotorCycle_ {
  /// see [MotorCycle.motorcycleId]
  static final motorcycleId =
      QueryIntegerProperty<MotorCycle>(_entities[1].properties[0]);

  /// see [MotorCycle.serialNumber]
  static final serialNumber =
      QueryStringProperty<MotorCycle>(_entities[1].properties[1]);

  /// see [MotorCycle.name]
  static final name =
      QueryStringProperty<MotorCycle>(_entities[1].properties[2]);

  /// see [MotorCycle.releaseYear]
  static final releaseYear =
      QueryStringProperty<MotorCycle>(_entities[1].properties[3]);
}
